<?php

namespace TomatoPHP\FilamentTenancy\Filament\Resources\TenantResource\RelationManagers;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\CreateAction;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\TextInput;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class DomainsRelationManager extends RelationManager
{
    protected static string $relationship = 'domains';

    public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return trans('filament-tenancy::messages.domains.title');
    }

    protected static function getModelLabel(): ?string
    {
        return trans('filament-tenancy::messages.domains.single'); // TODO: Change the autogenerated stub
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('domain')
                    ->required()
                    ->label(trans('filament-tenancy::messages.domains.columns.domain'))
                    ->prefix(request()->getScheme().'://')
                    ->suffix('.'.request()->getHost())
                    ->maxLength(255),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('domain')
            ->columns([
                TextColumn::make('domain')
                    ->label(trans('filament-tenancy::messages.domains.columns.domain')),
                TextColumn::make('full-domain')
                    ->label(trans('filament-tenancy::messages.domains.columns.full'))
                    ->getStateUsing(fn ($record) => Str::of($record->domain)->append('.')->append(request()->getHost())),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                CreateAction::make(),
            ])
            ->recordActions([
                EditAction::make(),
                DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
